server:
  port: 6000

spring:
  application:
    name: user
  datasource:
    username:
    password:
    url:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  web:
    resources:
      add-mappings: true
